config/routes.rb
Choseiyan::Application.routes.draw do
  root to: 'top#index'
  resources :top, param: :individual_url do
    collection do
      post :thanx
    end
  end
end

app/models/host_plans_date.rb
class HostPlansDate < ActiveRecord::Base
  belongs_to :schedule
end

app/models/plans_date.rb
class PlansDate < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  has_many :host_plans_dates
  accepts_nested_attributes_for :host_plans_dates

  JOIN        = 0
  NOT_DECIDED = 1
  CANT_JOIN   = 2

  JOIN_STATUS_HASH = {
    JOIN       => "◯",
    NOT_DECIDED => "△",
    CANT_JOIN  => "×"
  }

  def to_param
    return individual_url
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plans_dates_controller.rb
class PlansDatesController < ApplicationController
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    @schedule = Schedule.new
    @schedule.host_plans_dates.build
  end

  def create
    @schedule = Schedule.new(schedule_params)
    @schedule.individual_url = Digest::SHA1.hexdigest(Time.now.to_s)
    @schedule.save!
  end

  def show
    @schedule = Schedule.where(individual_url: params[:individual_url]).first
    @host_plans_dates = @schedule.host_plans_dates
    @plansdate_all_records = PlansDate.where(schedule_id: @schedule.id).all
    @plans_status_join = @plansdate_all_records.where(join_satus: Schedule::JOIN).all
    @plans_status_not_decided = @plansdate_all_records.where(join_satus: Schedule::NOT_DECIDED).all
    @plans_status_cant_join = @plansdate_all_records.where(join_satus: Schedule::CANT_JOIN).all
  end

  def thanx
    @schedule = Schedule.where(id: params[:schedule_id]).first
    params_start_day = params[:start_day]
    start_date= Date.new params_start_day["year"].to_i,
                         params_start_day["month"].to_i,
                         params_start_day["day"].to_i
    params_end_day = params[:end_day]
    end_date = Date.new params_end_day["year"].to_i,
                       params_end_day["month"].to_i,
                       params_end_day["day"].to_i
    @start_date_plus = start_date


    if start_date.month > end_date.month
      for m in start_date.month..12
        if m == start_date.month
          for d in start_date.day..@start_date_plus.end_of_month.day
            @the_created_day = Date.new @start_date_plus.year.to_i, m.to_i, d.to_i
            HostPlansDate.create(host_nominated_day: @the_created_day, schedule_id: params[:schedule_id])
          end
          @start_date_plus = @start_date_plus + 1.month
        elsif m == end_date.month
          for d in 1..end_date.day
            @the_created_day = Date.new @start_date_plus.year.to_i, m.to_i, d.to_i
            HostPlansDate.create(host_nominated_day: @the_created_day, schedule_id: params[:schedule_id])
          end
        else
          for d in 1..@start_date_plus.end_of_month.day
            @the_created_day = Date.new @start_date_plus.year.to_i, m.to_i, d.to_i
            HostPlansDate.create(host_nominated_day: @the_created_day, schedule_id: params[:schedule_id])
            @start_date_plus = @start_date_plus + 1.month
          end
        end
      end
      for m in 1..end_date.month
        if m == start_date.month
          for d in start_date.day..@start_date_plus.end_of_month.day
            @the_created_day = Date.new end_date.year.to_i, m.to_i, d.to_i
            HostPlansDate.create(host_nominated_day: @the_created_day, schedule_id: params[:schedule_id])
          end
          @start_date_plus = @start_date_plus + 1.month
        elsif m == end_date.month
          for d in 1..end_date.day
            @the_created_day = Date.new end_date.year.to_i, m.to_i, d.to_i
            HostPlansDate.create(host_nominated_day: @the_created_day, schedule_id: params[:schedule_id])
          end
        else
          for d in 1..@start_date_plus.end_of_month.day
            @the_created_day = Date.new end_date.year.to_i, m.to_i, d.to_i
            HostPlansDate.create(host_nominated_day: @the_created_day, schedule_id: params[:schedule_id])
            @start_date_plus = @start_date_plus + 1.month
          end
        end
      end
    else
      for m in start_date.month..end_date.month
        if m == start_date.month && m != end_date.month
          for d in start_date.day..@start_date_plus.end_of_month.day
            @the_created_day = Date.new @start_date_plus.year.to_i, m.to_i, d.to_i
            HostPlansDate.create(host_nominated_day: @the_created_day, schedule_id: params[:schedule_id])
          end
          @start_date_plus = @start_date_plus + 1.month
        elsif m == start_date.month && m == end_date.month
          for d in start_date.day..end_date.day
            @the_created_day = Date.new start_date.year.to_i, m.to_i, d.to_i
            HostPlansDate.create(host_nominated_day: @the_created_day, schedule_id: params[:schedule_id])
          end
        elsif m == end_date.month
          for d in 1..end_date.day
            @the_created_day = Date.new @start_date_plus.year.to_i, m.to_i, d.to_i
            HostPlansDate.create(host_nominated_day: @the_created_day, schedule_id: params[:schedule_id])
          end
        else
          for d in 1..@start_date_plus.end_of_month.day
            @the_created_day = Date.new @start_date_plus.year.to_i, m.to_i, d.to_i
            HostPlansDate.create(host_nominated_day: @the_created_day, schedule_id: params[:schedule_id])
          end
          @start_date_plus = @start_date_plus + 1.month
        end
      end

      redirect_to top_path(@schedule)
    end

    def edit
      @user = User.new
      @plans_date = PlansDate.new
      @schedule = Schedule.where(individual_url: params[:individual_url]).first
      @host_plans_dates = @schedule.host_plans_dates
    end

    def update
      @schedule.plans_date.create
      @plans_date = PlansDate.new
      @plans_date.save!
    end

  end



  private
  def schedule_params
    params.require(:schedule).permit(:title, :comment, :individual_url,
      host_plans_dates_attributes: [:id, :schdule_id, :host_nominated_day])
  end

  # def host_plans_dates_params
  #   params.require(:host_plans_date).permit(:host_nominated_day)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_dates_helper.rb
module PlansDatesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Choseiyan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/top/create.html.erb
<%= form_tag({ action: 'thanx' }, { method: 'post' }) do %>
  候補日程<br>
  開始日<%= select_date(Date.today, use_month_numbers: true, prefix: :start_day )%><br>
  終了日<%= select_date(Date.today, use_month_numbers: true, prefix: :end_day )%><br>
  <%= hidden_field_tag :schedule_id, @schedule.id %>
<%= submit_tag '日にち詳細に進む', class: '' %>
<% end %>

app/views/top/edit.html.erb
出席を入力する<br>

日にち候補<br>
<%= form_tag({ action: 'update' }, { method: :patch }) do %>
  <table>
    <thead>
      <tr>
        <th class="id">予定日</th>
        <th class="delete">◯</th>
        <th class="delete">△</th>
        <th class="delete">×</th>
      </tr>
    </thead>
      <tbody>
        表示名<br>
        <% text_field_tag :user_name, class: "form-basic" %>
        <% @host_plans_dates.each do |host_plans_date| %>
        <tr>
          <td>
            <%= host_plans_date.host_nominated_day %>

          <ul>
            <li class="form-item">
              <div class="form-right">
                <%= select_tag :join_status, options_for_select(Schedule::JOIN_STATUS_HASH.invert), class: 'form-basic' %>
              </div>
            </li>
          </ul>
         <% end %>
        </td>
        </tr>
      </tbody>
  </table>

    コメント<br><%= text_field_tag :user_comment %>
  <div><%= submit_tag "確認する" , class: "btn-basic" %></div>
  <% end %>

app/views/top/index.html.erb
イベント名
<%= form_for @schedule, url: top_index_path, method: :post do |f| %>
  <%= f.text_field :title, placeholder: '飲み会、バーベキュー'%>
  <br>
  メモ
  <br>
  <%= f.text_field :comment, placeholder: 'メモ' %>

  <%= f.submit'スケジュールを作成する' %>
<% end %>

app/views/top/show.html.erb
「<%= @schedule.title %>」の出欠確認<br>
<li>メモ</li>
<%= @schedule.comment %>
<table>
  <thead>
    <tr>
      <th class="id">予定日</th>
      <th class="delete">◯</th>
      <th class="delete">△</th>
      <th class="delete">×</th>


      </tr>
    </thead>

    <tbody>
      <% @host_plans_dates.each do |host_plans_date| %>
      <%  %>
      <tr>
        <td>
        <%= host_plans_date.host_nominated_day %>
        <%= host_plans_date %>

        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<%= link_to "出席を編集する", edit_top_path(@schedule)%>